version: "3.3"
services:
  translate:
    build: .
    restart: unless-stopped
    links:
      - mongo
    environment:
        MONGO_HOST: 'mongo'
        MONGO_PORT: '27017'
        MONGO_DATABASE: 'translate_db'
    depends_on:
    - mongo
    ports:
     - 3001:3000
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: 'translate_db'
    ports:
      - 27017:27017


